[package]
name = "linuxdeploy-plugin-polyfill_glibc"
edition = "2021"

[dependencies]
chromalog = "0.0.2"
clap = { version = "4.5.39", features = ["derive", "env"] }
elf = "0.8.0"
glob = "0.3.2"
subprocess = "0.2.9"
